#!/usr/bin/env bash
# SENTINEL Installer - BLE.sh Functions

install_blesh() {
  step "Installing BLE.sh to ${BLESH_DIR}"
  mkdir -p "${BLESH_DIR}"

  # Clone BLE.sh with optional commit verification
  if [[ -n "${BLESH_COMMIT:-}" ]]; then
    safe_git_clone --depth=1 --verify-commit="$BLESH_COMMIT" https://github.com/akinomyoga/ble.sh.git "${BLESH_DIR}"
  else
    safe_git_clone --depth=1 https://github.com/akinomyoga/ble.sh.git "${BLESH_DIR}"
  fi

  # Checkout specific tag if specified
  if [[ -n "${BLESH_TAG:-}" ]]; then
    if git -C "${BLESH_DIR}" rev-parse "$BLESH_TAG" >/dev/null 2>&1; then
      git -C "${BLESH_DIR}" checkout "$BLESH_TAG"
      ok "Checked out BLE.sh tag $BLESH_TAG"
    else
      warn "BLE.sh tag $BLESH_TAG not found; using default branch."
    fi
  else
    log "Using default BLE.sh branch (no specific tag configured)"
  fi

  # Check various potential locations for ble.sh
  if [[ ! -f "${BLESH_DIR}/ble.sh" ]]; then
    step "ble.sh not found, attempting to build it"

    # First try using make
    if [[ -f "${BLESH_DIR}/Makefile" ]]; then
      (cd "${BLESH_DIR}" && make) || warn "Make build failed, trying alternatives"
    fi

    # Check if ble.sh was generated in the out directory
    if [[ -f "${BLESH_DIR}/out/ble.sh" ]]; then
      # Create a symlink to the built file
      ln -sf "${BLESH_DIR}/out/ble.sh" "${BLESH_DIR}/ble.sh"
      ok "Created symlink to built ble.sh in out directory"
    elif [[ -f "${BLESH_DIR}/ble.pp" ]] && [[ -f "${BLESH_DIR}/make_command.sh" ]]; then
      # Try alternate build methods if needed
      warn "Built ble.sh not found in expected location, trying other approaches"
      (cd "${BLESH_DIR}" && bash make_command.sh) || warn "make_command.sh execution failed"
    fi

    # Final check if ble.sh exists anywhere
    if [[ ! -f "${BLESH_DIR}/ble.sh" ]] && [[ -f "${BLESH_DIR}/out/ble.sh" ]]; then
      ln -sf "${BLESH_DIR}/out/ble.sh" "${BLESH_DIR}/ble.sh"
      ok "Created symlink to ble.sh in out directory"
    elif [[ ! -f "${BLESH_DIR}/ble.sh" ]]; then
      fail "BLE.sh repository doesn't contain expected files and build failed"
    else
      ok "Successfully found/built ble.sh"
    fi
  fi

  # Install BLE.sh
  if ! make -C "${BLESH_DIR}" install PREFIX="${HOME}/.local" >/dev/null; then
    fail "BLE.sh make install failed. See logs for details."
  fi

  # Verify installation succeeded
  if [[ ! -f "${HOME}/.local/share/blesh/ble.sh" ]]; then
    fail "BLE.sh installation verification failed: ble.sh not found in ${HOME}/.local/share/blesh/"
  fi

  ok "BLE.sh installed"
}

create_blesh_loader() {
    local loader="${BLESH_LOADER}"

    # Recreate the loader if it was removed after a previous install
    if [[ -f "${loader}" ]] && ! is_done "BLESH_LOADER_DROPPED"; then
      mark_done "BLESH_LOADER_DROPPED"
      ok "BLE.sh loader already present at ${loader}"
      return
    fi

    if [[ ! -f "${loader}" ]]; then
      if is_done "BLESH_LOADER_DROPPED"; then
        warn "BLE.sh loader missing despite state file; recreating ${loader}"
      else
        step "Writing BLE.sh loader ${loader}"
      fi
      install -m 644 /dev/null "${loader}"
      cat > "${loader}" <<'EOF'
# Auto-generated by SENTINEL installer
# shellcheck shell=bash
if [[ -n ${SENTINEL_BLESH_LOADED:-} ]]; then return; fi
export SENTINEL_BLESH_LOADED=1
# Fix for 'unrecognized attach method' error
export BLESH_ATTACH_METHOD="attach"
BLESH_MAIN="${HOME}/.local/share/blesh/ble.sh"
if [[ -f ${BLESH_MAIN} ]]; then
  source "${BLESH_MAIN}" --attach=attach 2>/dev/null || echo "[install] Warning: Failed to load ble.sh" >&2
fi
EOF
      mark_done "BLESH_LOADER_DROPPED"
      ok "BLE.sh loader ready"
    else
      ok "BLE.sh loader already present at ${loader}"
    fi
}
